### ISSUE TITLE
V2- Alpha 3 - Departing Dillsboro for Wilmot train proceeds for Sylva instead

### ISSUE THREAD

**Issue by dtwilliams10** [Erabior/RouteManager#83]
Like the title says. I set Route Manager up to route from Sylva to Nantahala with every stop in between. Train arrived at Dillsboro, said it was departing for Wilmot and then proceeded to route towards Sylva instead. I disabled and reenabled RouteManager and when the train arrived at Whittier it then attempted to start heading back towards Wilmot.

**Comment by armyf35** [comment]
Can you please post your log file

**Comment by dtwilliams10** [comment]
[Player-prev.log](https://github.com/Erabior/RouteManager/files/13910771/Player-prev.log)

**Comment by dtwilliams10** [comment]
It did it again at the end of this log file. Except I left Hemingway with AlarkaJct on the list and it blew right through the station

**Comment by armyf35** [comment]
Hmm I wonder what stations you have selected when you enabled route mode? It looks like you were near Bryson and had at least Nantahala, so it determined the next stop to be Nantahala.

could you set the loglevel setting to trace in the ini file, that should show what stations are selected and would help, then send another log file with the issue. I should have asked for that before, my bad.

**Comment by dtwilliams10** [comment]
I had all the mainline stops between Hemingway and Nantahala (Alarka Jct, Almond, Nantahala). I'll change the logging level and try it again. It did it again last night when I was trying to get it to stop at Almond going towards Bryson after Nantahala.

**Comment by dtwilliams10** [comment]
New log file attached. This time I loaded the game with a train already stopped at Almond (after it blew through the station last night). It had passengers already loaded for Bryson Whittier and one other station. I added Alarka Jct, Hemingway, Bryson, Ela, Whittier, Wilmot, Dillsboro, and Sylva to the station list and hit enable. It immediately discharged all of the passengers except for ones slated for Alarka Junction. I stopped the train, backed up, and opened the passenger cars to find that they weren't selected to load for the first 4 stations I selected. I then hand selected the stations and set the road speed to 45. It then proceeded to blow through Alarka Jct, and Hemingway before I caught it heading into Bryson. 

[Player.log](https://github.com/Erabior/RouteManager/files/13920496/Player.log)

**Comment by armyf35** [comment]
That helped, just pushed a PR that should fix it. If you want to try with the fix I just made try this
[RouteManager.zip](https://github.com/Erabior/RouteManager/files/13922343/RouteManager.zip)

**Comment by dtwilliams10** [comment]
Looks like there is still an issue. I setup the route from Alarka Jct to run through Sylva with a stop at every station and it ran though Hemingway. Could it be ignoring the stop if there are no disembarking passengers? 

[Player.log](https://github.com/Erabior/RouteManager/files/13922530/Player.log)

**Comment by AdamC1228** [comment]
> Looks like there is still an issue. I setup the route from Alarka Jct to run through Sylva with a stop at every station and it ran though Hemingway. Could it be ignoring the stop if there are no disembarking passengers?
> 
> [Player.log](https://github.com/Erabior/RouteManager/files/13922530/Player.log)

While that is a planned feature (will require checking station and coaches for embarking / disembarking) that eventually will formally get implemented it should not be skipping any stations at this time. I will take a look this evening unless @armyf35 beats me to it.

**Comment by armyf35** [comment]
[RouteManager.zip](https://github.com/Erabior/RouteManager/files/13922979/RouteManager.zip) - Try this, should fix the issue below (Warning, I haven't tested this)
I am just doing a bit of guessing now, I think what occurred is the first time route mode was enabled it calculated the closest stop as alarka jct, with your next stop being hemingway, and the stations to stop at as hemingway, bryson, ela, whittier, wilmot, dillsboro, sylva. However after disabling and re-enabling it then initializes the next station as bryson since it thinks you went to hemingway

**Comment by dtwilliams10** [comment]
At first glance it's much better. Successfully stopped at Hemingway from Alarka and embarked passengers. It's continued on through to Whittier with stops at Bryson and Ela as well. I'll keep you posted if I see any further issues. I usually see some when I'm at the terminus and try to route the other way around the map.

**Comment by dtwilliams10** [comment]
Just a quick follow up, almost everything seems to be working as expected. One question I have is regarding routing to Cochran Station from Almond. It appears to go straight to Alarka Depot and hit Cochran on the way back down. Yet Cochran has passengers for Alarka that will now go un delivered. 

On that note, I'm curious about how to tell a train to pick up passengers for a station we're not planning to stop at. My thinking is I would run an Alarka mixed local from either Bryson or Alarka Jct up to Alarka Depot. But in order to gather passengers from around the map I need to tell the AI passenger train to stop at Alaska Depot and Cochran. Thoughts?

**Comment by AdamC1228** [comment]
That is due to the way alarka jct is configured and the current route logic. It's something that has been needing work but avoided while pondering how to handle it best.

**Comment by AdamC1228** [comment]
I have noted that Alarka JCT is problematic in the latest release (2.0.0.6 Beta). For the time being I am going to close this issue but do ask that you open a second issue with Alarka JCT for tracking purposes.
